background_opacity 0.81
tab_bar_style slant
detect_urls yes
copy_on_select yes
hide_window_decorations yes

shell_integration enabled

#term xterm-256color
term xterm-kitty
enabled_layouts horizontal
